version: '3'
services:
  # PYSPARK CONTAINER SETTINGS
  spark:
    build: .
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
    volumes:
      -./src:/app
  
  # POSTGRESQL CONTAINER SETTINGS 
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: